server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: blog-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 626488xqy
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.blog.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Logging
logging:
  level:
    com.example.blog: DEBUG
    com.baomidou.mybatisplus: DEBUG

# Spring Doc (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# JWT Configuration (to be configured later)
jwt:
  secret: your-secret-key-here
  expiration: 86400000 # 24 hours